baseURL = 'https://stan0930.github.io/'
languageCode = 'zh-cn'
title = "Stan's Blog"
theme = "PaperMod"

# 下面是 PaperMod 主题的一些常用小开关，你可以按需调整
[params]
    defaultTheme = "auto"      # 自动跟随系统切换深色/浅色模式
    ShowReadingTime = true     # 显示阅读时间估算
    ShowShareButtons = true    # 文章底部显示分享按钮
    ShowPostNavLinks = true    # 显示上一篇/下一篇文章链接
    ShowBreadCrumbs = true     # 显示面包屑导航